### ISSUE TITLE
Customisable flash key

### ISSUE THREAD

**Issue by designermonkey** [slimphp/Slim-Flash#10]
Please allow a customisable key in the constructor. This allows us to have multiple flash groups, `errors` and `warnings` for example.

**Comment by geggleto** [comment]
:+1:

**Comment by timwattenberg** [comment]
Which of the following options would be best:
1. `public function __construct(&$storage = null, $storageKey = 'slimFlash')`
2. `public function __construct($storageKey = 'slimFlash', &$storage = null)`
3. constructor with `$options`/`$settings` array

Option 1 would maintain BC, so I think it would be the best choice even though I think it's more likely to change the key than the storage itself.

**Comment by designermonkey** [comment]
Option 1 IMO.

**Comment by geggleto** [comment]
:+1: option 1
