### ISSUE TITLE
Flash messages for the current request

### ISSUE THREAD

**Issue by chrisvanpatten** [slimphp/Slim-Flash#13]
In Slim 2.x (which, admittedly, I never used!) it seems like it was possible to add a message to the current request, before the template was rendered, with the [`flashNow`](http://docs.slimframework.com/flash/now/) method.

Is this possible now, or are there plans to make this an option again?

Thanks!

**Comment by thinksalot** [comment]
Hi,

I hacked together a functionality for this in #14. `addMessageNow()` will allow you to add flashes for the current request.
