### ISSUE TITLE
Possible to allow html tags?

### ISSUE THREAD

**Issue by matthijs110** [slimphp/Slim-Flash#15]
Hello,

Is it possible to allow HTML tags?
For `example:

``` php
$this->flash->addMessage('global', 'You have an issue at <strong>this field</strong>!'
```

It outputs without the `<strong>` markup. The message contains literal:

``` html
You have an issue at <strong>this field</strong>!
```

Instead of:

> You have an issue at **this field**!

**Comment by krydos** [comment]
@matthijs110 hi,
actually it works as you expect. There is no any tags escaping or something similar. If you can describe the way how you're getting message and how you're displaying it then I may try to help you.

**Comment by matthijs110** [comment]
@KryDos 

Hey,

I actually forgot to say that I fixed my issue by using the following code:

``` twig
{{ flash.getMessage('warning').0|raw }}
```

The `raw` bit fixed the issue :+1:
