### ISSUE TITLE
Show messages on twig without reload / redirecting 

### ISSUE THREAD

**Issue by sayaamirul** [slimphp/Slim-Flash#17]
I have a view with a form, i want show the flash messages if my form validation got fail, the  problem is when showing messages to my view, the messages just showed when the page is reloaded , or when redirecting to other routes/view ...

**Comment by deflox** [comment]
How did you even get the message in the twig view? I'm trying to figuring this out for 2 hours now but I just don't get the message...

**Comment by sayaamirul** [comment]
Adding flash to global variable in twig container, this our [Current Code](https://github.com/dda2/Pamit/), may help you.

**Comment by deflox** [comment]
Thanks I will take a look at it.

Found a solution after asking my question on [stackoverflow](http://stackoverflow.com/questions/35210298/slimphp-v3-how-to-display-flash-message-on-view).

The answer may help you too.

**Comment by sayaamirul** [comment]
Thanks a lot , really helpful ...

**Comment by akrabat** [comment]
Use `addMessageNow()` to add a message to be retrieved in the same request.
