### ISSUE TITLE
Passing arrays not working propably

### ISSUE THREAD

**Issue by timwattenberg** [slimphp/Slim-Flash#18]
I'm experiencing an issue where an array is not passed probably via flash messages.

I followed the setup from the README, further setup:

``` php
// First request
$this->flash->addMessage('inputs', ['test' => 'input']);

// Second request
var_dump($this->flash->getMessages()['inputs'][0]); // => string(5) "Array"
```

**Comment by ManeVenture** [comment]
I was experiencing a similar issue, which was strange to me when considering the readme note below Usage: 
"Please note that a message could be a string, object or array. Please check what your storage can handle."

I took a look at the src and noticed this:

```
public function addMessage($key, $message)
    {
        //Create Array for this key
        if (!isset($this->storage[$this->storageKey][$key])) {
            $this->storage[$this->storageKey][$key] = array();
        }

        //Push onto the array
        $this->storage[$this->storageKey][$key][] = (string)$message;
    }
```

Notice in the push the type cast to (string).  Given the note I am unsure if this is intended for the final design.  For my purpose I have removed this typecasting.  (Be warned that there may be unintended results from doing so)

**Comment by timwattenberg** [comment]
@ManeVenture This is already fixed in the upstream version, but since there is no official release other then 0.1.0 composer uses this by default (which still has the type cast).
