### ISSUE TITLE
Persisting across redirects

### ISSUE THREAD

**Issue by trasher** [slimphp/Slim-Flash#25]
Hello,

In some cases, I can have multiple redirections in my app; wich will cause my flash messages to be lost.
Back to Slim2, I got the same problem I was able to solve using the `flashKeep()` method.

Right now, I'm able to retrieve it by manually getting message, and settign them back again with `addMessage`; but that only works for one level redirection, I can have two :/

How should I resolve this? Is there a way to get kind of `flashKeep()` behaviour?

Thank you :)

**Comment by krotovic** [comment]
I think, it is possible, you can extend `Slim\Flash\Messages::addMessage` to add your persistent message to another `$_SESSION` key (e.g. `$_SESSION["flash_persistent"]`).
But if I were you I would rethink why I need multiple redirections in my app.

**Comment by trasher** [comment]
Hello,

You are right, I should not have multiple redirections; this is just the actual behavior and it will be quite difficult to fix (quite hard to find). But I do think this is the way to go :)

Thank you!
