### ISSUE TITLE
Default value to getMessage()

### ISSUE THREAD

**Issue by cdarken** [slimphp/Slim-Flash#31]
Have you thought about adding a second parameter to getMessage() to allow for overriding the default 'null' value in case the key does not exist?

**Comment by akrabat** [comment]
As `getMessage()` returns an array of messages, I don't see any need for a default. However, [`getFirstMessage()`](https://github.com/slimphp/Slim-Flash/blob/44347770b1573d23a7ba4f6eb95dc583d1b172be/src/Messages.php#L153) does have a second parameter for the default to return.
