### ISSUE TITLE
New method: setMessage

### ISSUE THREAD

**Issue by cdarken** [slimphp/Slim-Flash#32]
I have a suggestion: wouldn't be useful to have a method that just sets a flash message without adding to an array? For instance if we have an array of validation errors. It would work like this:

```php
// setting
flash->setMessage('errors', [...])

// retrieving
$errors = flash->getMessage('errors');
// send the errors to the template
```

**Comment by akrabat** [comment]
This is handled better by ['getFirstMessage()'](https://github.com/slimphp/Slim-Flash/blob/44347770b1573d23a7ba4f6eb95dc583d1b172be/src/Messages.php#L153).
