### ISSUE TITLE
Returning message(s) stored for next request

### ISSUE THREAD

**Issue by pridit** [slimphp/Slim-Flash#36]
We have `getMessages()` which is returning from the previous request, and everything is a derivative of this. I want messages to be sent to the next request, but also retrieve them within the current logic I am doing prior to that for validation or otherwise.

I would need to be accessing `$this->storage[$this->storageKey]` to get anything currently stored for the next request.

Please let me know whether it's viable to add a new method to support this, or I am just being stupid and missing something overt that achieves what I'm aiming for.

**Comment by lezhnev74** [comment]
Just stumbled upon this issue.
I am writing this pseudo code:
```
- validate many input fields
- if field is wrong - call `addMessage()`
- I thought I could know if there were problems with just polling flashMessages APIs... But there is no such method.
```
`getMessages()` returns data from previous/current request, but not ones queued for the next one.

**Comment by MicahStevens** [comment]
I see your note in the GIT log about the getHostByName. I'll take your word for it. It's not strictly necessary, that's for sure.

**Comment by ve3** [comment]
I think I have the same problem.
My process.
* Page one call `addMessage()` for 2 messages (2 keys).
* Page two call `getMessage('key1')`. The message display correctly but there is one more key left uncalled.
* Page two make ajax request to get common pages data.
* The common pages data controller call `getMessage('key2')` which is never call before. This should displaying message for `key2` but there is nothing left after call to `key1`.

**Comment by odan** [comment]
Slim-Flash relies on PHP sessions to store flash messages, and if the session isn't started or managed correctly within the middleware, the flash messages won't persist as expected.

Make sure that the session is properly started before trying to set or retrieve flash messages. For example a middleware could be used to correctly start the session handler.
