### ISSUE TITLE
Is we dont need to clear the message?

### ISSUE THREAD

**Issue by aalfiann** [slimphp/Slim-Flash#38]
Just want to know about this flash messages,

I have create some test with this library and this is working fine,

but I can not get the message twice, actualy i didn't clear the message.

then i check the message with hasMessage('test') function and the result is null.

Is we dont need to clear the message? is it already cleared as default? or this is a bug?

Where is the session gone?

Thanks.

**Comment by akrabat** [comment]
Flash messages are automatically cleared, so that they only appear on the following request and never on any subsequent requests. If you need it to persist longer, then use a normal session variable.
